### ISSUE TITLE
cannot load such file -- chef/provisioning/lxc_driver/lxc_provisioner

### ISSUE THREAD

**Issue by q53** [chef/chef-provisioning-lxc#8]
Actually subj.
Details:
chef-node - Scientific Linux 7.0
chef-client - offical chef-12.0.3-1 rpm
Here is cookbook:
```
%w{chef-provisioning chef-provisioning-lxc}.each do |pkg|
  chef_gem "#{pkg}" do
    action :install
  end
end

case node['platform_family']
when  'rhel', 'fedora'
  package 'lxc-devel'
end

require 'chef/provisioning'
require 'chef/provisioning/lxc_driver/lxc_provisioner'
with_provisioner Chef::Provisioning::LXCDriver::LXCProvisioner.new
with_provisioner_options :template => 'sl', :template_options => %w(--fqdn test-2.dev.cloud.lan -a x86_64)
machine 'test-2' do 
  chef_environment 'dev'
  role 'base-role'
  recipe 'rabbitmq'
end

```
Hire is client log:
```
Starting Chef Client, version 12.0.3
[2015-02-18T23:27:11+03:00] INFO: *** Chef 12.0.3 ***
[2015-02-18T23:27:11+03:00] INFO: Chef-client pid: 18739
[2015-02-18T23:27:12+03:00] INFO: Run List is [role[base-role], recipe[provision]]
[2015-02-18T23:27:12+03:00] INFO: Run List expands to [user::data_bag, chef-client, dev-base, provision]
[2015-02-18T23:27:12+03:00] INFO: Starting Chef Run for sl7test
[2015-02-18T23:27:12+03:00] INFO: Running start handlers
[2015-02-18T23:27:12+03:00] INFO: Start handlers complete.
[2015-02-18T23:27:12+03:00] INFO: HTTP Request Returned 404 Not Found: 
...
[2015-02-18T23:27:13+03:00] INFO: Storing updated cookbooks/provision/recipes/default.rb in the cache.
  - provision
Compiling Cookbooks...
Recipe: provision::default
  * chef_gem[chef-provisioning] action install[2015-02-18T23:27:13+03:00] INFO: Processing chef_gem[chef-provisioning] action install (provision::default line 11)
 (up to date)
  * chef_gem[chef-provisioning-lxc] action install[2015-02-18T23:27:13+03:00] INFO: Processing chef_gem[chef-provisioning-lxc] action install (provision::default line 11)
 (up to date)
  
  ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/provision/recipes/default.rb
  ================================================================================
  
  LoadError
  ---------
  cannot load such file -- chef/provisioning/lxc_driver/lxc_provisioner
  
  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/provision/recipes/default.rb:22:in `from_file'
  
  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/provision/recipes/default.rb:
  
   15:  
   16:  case node['platform_family']
   17:  when  'rhel', 'fedora'
   18:    package 'lxc-devel'
   19:  end
   20:  
   21:  require 'chef/provisioning'
   22>> require 'chef/provisioning/lxc_driver/lxc_provisioner'
   23:  with_provisioner Chef::Provisioning::LXCDriver::LXCProvisioner.new
   24:  with_provisioner_options :template => 'sl', :template_options => %w(--fqdn test-2.dev.cloud.lan -a x86_64)
   25:  machine 'test-2' do 
   26:    chef_environment 'dev'
   27:    role 'base-role'
   28:    recipe 'rabbitmq'
   29:  end
   30:  
   31:  
  
  
  Running handlers:
[2015-02-18T23:27:13+03:00] ERROR: Running exception handlers
  Running handlers complete
[2015-02-18T23:27:13+03:00] ERROR: Exception handlers complete
[2015-02-18T23:27:13+03:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
  Chef Client failed. 0 resources updated in 2.048890796 seconds
[2015-02-18T23:27:13+03:00] ERROR: cannot load such file -- chef/provisioning/lxc_driver/lxc_provisioner
[2015-02-18T23:27:13+03:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

```

**Comment by jkeiser** [comment]
The issue you are having is that the README and example cookbooks were wrong :/  It's fixed now.  Your recipe should look like this:

```ruby
%w{chef-provisioning chef-provisioning-lxc}.each do |pkg|
  chef_gem "#{pkg}" do
    action :install
  end
end

case node['platform_family']
when  'rhel', 'fedora'
  package 'lxc-devel'
end

require 'chef/provisioning'
with_driver 'lxc'
with_machine_options :template => 'sl', :template_options => %w(--fqdn test-2.dev.cloud.lan -a x86_64)
machine 'test-2' do 
  chef_environment 'dev'
  role 'base-role'
  recipe 'rabbitmq'
end
```

Sorry about that!  Please reopen/comment here if the same problem is occurring, or feel free to open a new issue if something new comes up and we'll get on it :)  Thanks!

**Comment by q53** [comment]
Still does not work:
```
    ================================================================================
    Error executing action `converge` on resource 'machine[test-2]'
    ================================================================================
    
    LoadError
    ---------
    cannot load such file -- chef/provisioning/lxc_driver/lxc_driver
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/provision/recipes/default.rb
    
     24: machine 'test-2' do
     25:   chef_environment 'dev'
     26:   role 'base-role'
     27:   recipe 'rabbitmq'
     28: end
     29: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/provision/recipes/default.rb:24:in `from_file'
    
    machine("test-2") do
      action :converge
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_environment "dev"
      chef_server {:chef_server_url=>"https://192.168.6.20/organizations/sesurity", :options=>{:client_name=>"sl7test", :signing_key_filename=>"/etc/chef/client.pem"}}
      driver "lxc"
      machine_options {:template=>"sl", :template_options=>["--fqdn", "test-2.dev.cesurity.cloud.lan", "-a", "x86_64"]}
      declared_type :machine
      cookbook_name "provision"
      recipe_name "default"
      run_list_modifiers [#<Chef::RunList::RunListItem:0x0000000530a408 @version=nil, @type=:role, @name="base-role">, #<Chef::RunList::RunListItem:0x0000000530a250 @version=nil, @type=:recipe, @name="rabbitmq">]
    end
```

**Comment by q53** [comment]
Still does not work:
```
    ================================================================================
    Error executing action `converge` on resource 'machine[test-2]'
    ================================================================================
    
    LoadError
    ---------
    cannot load such file -- chef/provisioning/lxc_driver/lxc_driver
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/provision/recipes/default.rb
    
     24: machine 'test-2' do
     25:   chef_environment 'dev'
     26:   role 'base-role'
     27:   recipe 'rabbitmq'
     28: end
     29: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/provision/recipes/default.rb:24:in `from_file'
    
    machine("test-2") do
      action :converge
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_environment "dev"
      chef_server {:chef_server_url=>"https://192.168.6.20/organizations/org", :options=>{:client_name=>"sl7test", :signing_key_filename=>"/etc/chef/client.pem"}}
      driver "lxc"
      machine_options {:template=>"sl", :template_options=>["--fqdn", "test-2.dev.cloud.lan", "-a", "x86_64"]}
      declared_type :machine
      cookbook_name "provision"
      recipe_name "default"
      run_list_modifiers [#<Chef::RunList::RunListItem:0x0000000530a408 @version=nil, @type=:role, @name="base-role">, #<Chef::RunList::RunListItem:0x0000000530a250 @version=nil, @type=:recipe, @name="rabbitmq">]
    end
```
